development:
  adapter: postgresql
  encoding: unicode
  database: notebook_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: notebook_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: notebook_production
  pool: 5
  password: